import ContextCoreTypes

public typealias ConsolidationEpisodicStore = ContextCoreTypes.ConsolidationEpisodicStore
public typealias ConsolidationSemanticStore = ContextCoreTypes.ConsolidationSemanticStore
